### PR TITLE
update 1.19 data and schema

### PR DESCRIPTION
**Pull request by Eejit43**

### CODE REVIEW

**Comment by Lianecx** [comment]
Id seems pretty unnecessary to me. Its just category/name

**Comment by Eejit43** [comment]
yes but it is a still part of the data, and people will likely wish to find advancements by id

**Comment by Lianecx** [comment]
> yes but it is a still part of the data, and people will likely wish to find advancements by id

Hmm okay, what about a criteria list?

**Comment by Eejit43** [comment]
> > yes but it is a still part of the data, and people will likely wish to find advancements by id
> 
> Hmm okay, what about a criteria list?

Still thinking about how to do that, as some have huge criteria lists

**Comment by Lianecx** [comment]
Oops i removed the draft

**Comment by Lianecx** [comment]
> > > yes but it is a still part of the data, and people will likely wish to find advancements by id
> > 
> > 
> > Hmm okay, what about a criteria list?
> 
> Still thinking about how to do that, as some have huge criteria lists

Does that matter? You dont need to specify a lot details, just an array of names/ids

**Comment by Eejit43** [comment]
> > > > yes but it is a still part of the data, and people will likely wish to find advancements by id
> > > 
> > > 
> > > Hmm okay, what about a criteria list?
> > 
> > 
> > Still thinking about how to do that, as some have huge criteria lists
> 
> Does that matter? You dont need to specify a lot details, just an array of names/ids

well some are triggered by getting an item, crafting an item, visiting an area, etc., which I'd say needs to be included somehow

**Comment by Lianecx** [comment]
> > > > > yes but it is a still part of the data, and people will likely wish to find advancements by id
> > > > 
> > > > 
> > > > Hmm okay, what about a criteria list?
> > > 
> > > 
> > > Still thinking about how to do that, as some have huge criteria lists
> > 
> > 
> > Does that matter? You dont need to specify a lot details, just an array of names/ids
> 
> well some are triggered by getting an item, crafting an item, visiting an area, etc., which I'd say needs to be included somehow

Make the criterial list a list of objects and add the ‚trigger‘ and ‚name‘ field

**Comment by Eejit43** [comment]
> > > > > > yes but it is a still part of the data, and people will likely wish to find advancements by id
> > > > > 
> > > > > 
> > > > > Hmm okay, what about a criteria list?
> > > > 
> > > > 
> > > > Still thinking about how to do that, as some have huge criteria lists
> > > 
> > > 
> > > Does that matter? You dont need to specify a lot details, just an array of names/ids
> > 
> > 
> > well some are triggered by getting an item, crafting an item, visiting an area, etc., which I'd say needs to be included somehow
> 
> Make the criterial list a list of objects and add the ‚trigger‘ and ‚name‘ field

here is an example:

```text
{
  "parent": "minecraft:adventure/root",
  "criteria": {
    "voluntary_exile": {
      "conditions": {
        "entity": [
          {
            "condition": "minecraft:entity_properties",
            "entity": "this",
            "predicate": {
              "type": "#minecraft:raiders",
              "equipment": {
                "head": {
                  "items": [
                    "minecraft:white_banner"
                  ],
                  "nbt": "{BlockEntityTag:{Patterns:[{Color:9,Pattern:\"mr\"},{Color:8,Pattern:\"bs\"},{Color:7,Pattern:\"cs\"},{Color:8,Pattern:\"bo\"},{Color:15,Pattern:\"ms\"},{Color:8,Pattern:\"hh\"},{Color:8,Pattern:\"mc\"},{Color:15,Pattern:\"bo\"}],id:\"minecraft:banner\"},HideFlags:32,display:{Name:'{\"color\":\"gold\",\"translate\":\"block.minecraft.ominous_banner\"}'}}"
                }
              }
            }
          }
        ]
      },
      "trigger": "minecraft:player_killed_entity"
    }
  },
  "display": {
    "announce_to_chat": true,
    "description": {
      "translate": "advancements.adventure.voluntary_exile.description"
    },
    "frame": "task",
    "hidden": true,
    "icon": {
      "item": "minecraft:white_banner",
      "nbt": "{BlockEntityTag:{Patterns:[{Color:9,Pattern:\"mr\"},{Color:8,Pattern:\"bs\"},{Color:7,Pattern:\"cs\"},{Color:8,Pattern:\"bo\"},{Color:15,Pattern:\"ms\"},{Color:8,Pattern:\"hh\"},{Color:8,Pattern:\"mc\"},{Color:15,Pattern:\"bo\"}],id:\"minecraft:banner\"},HideFlags:32,display:{Name:'{\"color\":\"gold\",\"translate\":\"block.minecraft.ominous_banner\"}'}}"
    },
    "show_toast": true,
    "title": {
      "translate": "advancements.adventure.voluntary_exile.title"
    }
  },
  "requirements": [
    [
      "voluntary_exile"
    ]
  ]
}
```

**Comment by Eejit43** [comment]
I'll need to try and adapt that into a more readable format

**Comment by Eejit43** [comment]
maybe just including the `requirements` field is enough...

**Comment by Eejit43** [comment]
There it is with just requirements, I'll see about adapting `criteria` as well

**Comment by Eejit43** [comment]
with criteria, I don't think I can really shorten it from: [advancements.txt](https://github.com/Lianecx/minecraft-data/files/8959146/advancements.txt)

**Comment by Lianecx** [comment]
> with criteria, I don't think I can really shorten it from: [advancements.txt](https://github.com/Lianecx/minecraft-data/files/8959146/advancements.txt)

I mean if you just have the trigger (i.e. location or inventory_changed) and a name (i.e. bastion or wither_skull) thats pretty much everything you need

**Comment by Lianecx** [comment]
The requirements are definitely very helpful already

**Comment by Eejit43** [comment]
was doing something else, I'll put that together in a bit

**Comment by Lianecx** [comment]
> was doing something else, I'll put that together in a bit

Okay, looking foward to seeing that :D

**Comment by Lianecx** [comment]
I would actually make an array of criteria with name and trigger properties

**Comment by Eejit43** [comment]
> I would actually make an array of criteria with name and trigger properties

different from what it currently is?

**Comment by Lianecx** [comment]
> > I would actually make an array of criteria with name and trigger properties
> 
> different from what it currently is?

Not really, I think its great 👍

**Comment by Lianecx** [comment]
Dont forget to update the schmeatic

**Comment by Eejit43** [comment]
> Dont forget to update the schmeatic

yep will do, I'm working on adding some more checks so more information is given in the criteria :)

**Comment by Eejit43** [comment]
don't merge quite yet but I believe that should be everything that I can add

**Comment by Eejit43** [comment]
@Lianecx opinions? might be ready to merge

**Comment by Lianecx** [comment]
**Missing:**
- Item and Block type for `item_used_on_block`.
- Item type for `player_hurt_entity` (adventure/shoot_arrow, adventure/throw_trident)
- Height information for `villager_trade` (adventure/trade_at_world_height)
- Entity type for `channeled_lightning` (adventure/very_very_frightening, adventure/lightning_rod_with_villager_no_fire)
- Block and Item type for `location` (adventure/walk_on_powder_snow_with_leather_boots)
- Block information for `enter_block` (end/enter_end_gateway)
- Heigt information for `levitation` (end/levitate)
- Entity type for `effects_changed` (husbandry/kill_axolotl_target) (Might be confusing because its the source entity that caused the effect_change)
- Effect types for `effects_changed` (nether/all_potions, nether/all_effects)
- Block types for `placed_block` (husbandry/plant_seed)
- Enchantment type and num of bees for `bee_nest_destroyed` (husbandry/silk_touch_nest)
- Level of beacon for `construct_beacon` (nether/create_full_beacon, nether/create_beacon)
- Distance information for `nether_travel` (nether/fast_travel)
- Dimension type for `changed_dimensions` (nether/root, story/enter_the_end, story/enter_the_nether)

Not all of these are necessarily needed but theres definitely a bunch that should to be added

**Comment by Eejit43** [comment]
Additionally entity type in `lightning_rod_with_villager_no_fire`

will fix those in a sec, thanks!!

**Comment by Lianecx** [comment]
> 



> Additionally entity type in `lightning_rod_with_villager_no_fire`
> 
> will fix those in a sec, thanks!!

I think thats the same entity type as in `adventure/very_very_frightening` (trigger: `channeled_lightning`). I just forgot to list that advancement there

**Comment by Lianecx** [comment]
I accidentally clicked on ready for review again ....

**Comment by Eejit43** [comment]
@Lianecx that should be everything I believe

**Comment by Lianecx** [comment]
“The number of bees inside of an advancement” 🤣
I think you should redo the descriptions to something like:
“The required block to complete the advancement.” or “The number of bees inside of a bee nest that is required to complete the advancement.”

**Comment by Lianecx** [comment]
Also, why is the beacon level one of string or number? Isnt it always number?

**Comment by Eejit43** [comment]
> “The number of bees inside of an advancement” 🤣 I think you should redo the descriptions to something like: “The required block to complete the advancement.” or “The number of bees inside of a bee nest that is required to complete the advancement.”

Check the commit right before you sent that :)

**Comment by Eejit43** [comment]
> Also, why is the beacon level one of string or number? Isnt it always number?

object or number (will fix), one includes an object with a min

**Comment by Lianecx** [comment]
> > “The number of bees inside of an advancement” 🤣 I think you should redo the descriptions to something like: “The required block to complete the advancement.” or “The number of bees inside of a bee nest that is required to complete the advancement.”
> 
> Check the commit right before you sent that :)

Now the descriorion is a little short and doesnt really say what the properties are required for. I think you should suffix: “to complete the advancement.”

**Comment by Eejit43** [comment]
> > > “The number of bees inside of an advancement” 🤣 I think you should redo the descriptions to something like: “The required block to complete the advancement.” or “The number of bees inside of a bee nest that is required to complete the advancement.”
> > 
> > 
> > Check the commit right before you sent that :)
> 
> Now the descriorion is a little short and doesnt really say what the properties are required for. I think you should suffix: “to complete the advancement.”

I'd say that's inferred and unnecessary but I'll add it if you want

**Comment by Lianecx** [comment]
> > > > “The number of bees inside of an advancement” 🤣 I think you should redo the descriptions to something like: “The required block to complete the advancement.” or “The number of bees inside of a bee nest that is required to complete the advancement.”
> > > 
> > > 
> > > Check the commit right before you sent that :)
> > 
> > 
> > Now the descriorion is a little short and doesnt really say what the properties are required for. I think you should suffix: “to complete the advancement.”
> 
> I'd say that's inferred and unnecessary but I'll add it if you want

Yeah, thatd be cool. Also, for the trigger it should be: “The trigger of an advancement” because technically its not “required”

**Comment by Lianecx** [comment]
Item and entity arrays can contain items or entities that contain arrays… of what?

**Comment by Lianecx** [comment]
Theres also arrays of “null” they should be deleted

**Comment by Eejit43** [comment]
> Item and entity arrays can contain items or entities that contain arrays… of what?

items/entities. I'm not sure if there are instances of that but they are inside arrays so I accounted for possibly being arrays rather than just strings

**Comment by Eejit43** [comment]
> Theres also arrays of “null” they should be deleted

thanks I'll fix that

**Comment by Lianecx** [comment]
> > Item and entity arrays can contain items or entities that contain arrays… of what?
> 
> items/entities. I'm not sure if there are instances of that but they are inside arrays so I accounted for possibly being arrays rather than just strings

Not sure what you mean. When do the lists contain arrays?

**Comment by Eejit43** [comment]
> > > Item and entity arrays can contain items or entities that contain arrays… of what?
> > 
> > 
> > items/entities. I'm not sure if there are instances of that but they are inside arrays so I accounted for possibly being arrays rather than just strings
> 
> Not sure what you mean. When do the lists contain arrays?

appears they don't, the json is just set up weirdly in that case `¯\_(ツ)_/¯`, will fix

**Comment by Lianecx** [comment]
Okay, ill merge this pr tmr after school (if you dont find any other issues) :D

**Comment by Eejit43** [comment]
> Okay, ill merge this pr tmr after school (if you dont find any other issues) :D

almost finished, think you can merge it in like ~3 minutes?

**Comment by Lianecx** [comment]
Okau i guess

**Comment by Eejit43** [comment]
> Okau i guess

should be ready to merge!

I'll open another PR if anything else needs changed

**Comment by Lianecx** [comment]
Awesome 👏

**Pull request merged**
