### PR TITLE
update/add advancements

### PR DESCRIPTION
**Pull request by Eejit43**
Todo:

- [x] update 1.19
- [x] 1.18
- [x] 1.17
- [x] 1.16
- [x] 1.15
- [x] 1.14
- [x] 1.13
- [x] 1.12
- [x] update schema

### CODE REVIEW

**Comment by Lianecx** [comment]
Y distance should be changed to vertical

**Comment by Lianecx** [comment]
And items are not always an array (for example `play_jukebox_in_meadows`

**Comment by Eejit43** [comment]
> Y distance should be changed to vertical

that is how it is in the actual data, I might change it however

**Comment by Eejit43** [comment]
> And items are not always an array (for example `play_jukebox_in_meadows`

I'm aware that is fixed when I push the next commit, thanks :+1:

**Comment by Lianecx** [comment]
> > Y distance should be changed to vertical
> 
> that is how it is in the actual data, I might change it however

Well you also changed X to horizonatal so it wouldnt make sense to have Y instead of vertical

**Comment by Lianecx** [comment]
It does make sense to keep Y for the position though as it is a coordinate

**Comment by Eejit43** [comment]
> > > Y distance should be changed to vertical
> > 
> > 
> > that is how it is in the actual data, I might change it however
> 
> Well you also changed X to horizonatal so it wouldnt make sense to have Y instead of vertical

I did not change it, that is how the original data is

**Comment by Lianecx** [comment]
Okay i think we should change it to vertical though to be more consistent

**Comment by Eejit43** [comment]
It will take a while for the rest of them as they are formatted quite differently, but I'll have them relatively soon hopefully

**Comment by Lianecx** [comment]
> It will take a while for the rest of them as they are formatted quite differently, but I'll have them relatively soon hopefully

Did the formatting change that much over the versions? 1.13 changed some stuff i think but what about the other versions?

**Comment by Eejit43** [comment]
> > It will take a while for the rest of them as they are formatted quite differently, but I'll have them relatively soon hopefully
> 
> Did the formatting change that much over the versions? 1.13 changed some stuff i think but what about the other versions?

yes, it did. mostly stuff changing from arrays of objects to direct objects

**Comment by Eejit43** [comment]
I'm working on something else right now but I should be able to get back to it and complete 1.15 shortly

**Comment by Lianecx** [comment]
No worries :D 
Theres no need to rush this. You could send me the tool and i can helo you add the remaining versions if you want

**Comment by Eejit43** [comment]
> No worries :D Theres no need to rush this. You could send me the tool and i can helo you add the remaining versions if you want

I might but that would be annoying as mass changes have to be made to the tool to account for older versions so that would just cause conflicts. I'll work on it for right now but will let you know!

**Comment by Lianecx** [comment]
> > No worries :D Theres no need to rush this. You could send me the tool and i can helo you add the remaining versions if you want
> 
> I might but that would be annoying as mass changes have to be made to the tool to account for older versions so that would just cause conflicts. I'll work on it for right now but will let you know!

I would just be editing the tool locally stored on my computer so it wouldnt really make conflicts with yours

**Comment by Eejit43** [comment]
> > > No worries :D Theres no need to rush this. You could send me the tool and i can helo you add the remaining versions if you want
> > 
> > 
> > I might but that would be annoying as mass changes have to be made to the tool to account for older versions so that would just cause conflicts. I'll work on it for right now but will let you know!
> 
> I would just be editing the tool locally stored on my computer so it wouldnt really make conflicts with yours

yes I know but for some of this it affects other versions. anyway doesn't matter seems like the changes in 1.15 were the most major, so it should be hopefully a bit easier for the rest

**Comment by Lianecx** [comment]
Okay 👍

**Comment by Eejit43** [comment]
@Lianecx do you think I should replace all occurances of `minecraft: ` or leave it be? I think that would make it easier to access the info

**Comment by Lianecx** [comment]
> @Lianecx do you think I should replace all occurances of `minecraft: ` or leave it be? I think that would make it easier to access the info

Hmm, im not really sure. I think most of the times you dont need the prefix but I would ask u9g or some other developer about that.

**Comment by Lianecx** [comment]
Its not included in any of the other data files so removing it is probably the best idea

**Comment by Eejit43** [comment]
> Its not included in any of the other data files so removing it is probably the best idea

sounds good I'll do that in a bit

**Comment by Eejit43** [comment]
@Lianecx take a look, should be good to go!

**Comment by Lianecx** [comment]
`block` -> `block array` In schema

**Comment by Lianecx** [comment]
And did you add wearing to the schema? I cant find it

**Comment by Lianecx** [comment]
`Wearing` is a bit weird. Why is it sometimes an array? It should always be an object with the properties: head, chest, leggings, feet. And the values shouldnt be a n object with just the single property `item` but rather just a string with the item e.g.

“wearing”: {
“head”: “golden_helmet”,
”chest”: “diamond_chestplate”
}

**Comment by Eejit43** [comment]
> `Wearing` is a bit weird. Why is it sometimes an array? It should always be an object with the properties: head, chest, leggings, feet. And the values shouldnt be a n object with just the single property `item` but rather just a string with the item e.g.
> 
> “wearing”: { “head”: “golden_helmet”, ”chest”: “diamond_chestplate” }

It is sometimes an array as for `distract_piglin` and `distract_piglin_directly` you must have at one of the golden armor pieces, not all.

I could change `wearing`, but I won't change `entityWearing` as that can include NBT data
The purpose of keeping it like that was to account for any future changes that might add NBT to requirements

**Comment by Eejit43** [comment]
> And did you add wearing to the schema? I cant find it

yeah? line `228`

**Comment by Lianecx** [comment]
So this is done?

**Comment by Eejit43** [comment]
> So this is done?

well would you like me to change `wearing`? just pushed a schema fix, which is the last thing if not

**Comment by Lianecx** [comment]
I guess wearing is fine like that. I dont really like that it can be an array or an object but i dont know another way of saying you only need one

**Pull request merged**
